title: Dovilė Cibulskaitė
order_email: labas@cibulskaite.lt
instagram_url: https://instagram.com/cibulskaitedovile
messenger_url: https://m.me/cibulskaitedovile

baseurl: "" # the subpath of your site, e.g. /blog
url: https://cibulskaite.lt

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
  sass_dir: _scss

collections:
  work:
    output: true

defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
